#!/bin/bash
# -*- bash -*-

# This gives you access to the custom DSL
. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"

# Everything past this point is the custom DSL which is optional

# Install a specific version of Ansible, you can
# omit the version to install devel (latest unstable)
install_ansible ${test_ansible_version}

ansible-galaxy install -f erasme.nginx

# An assertion which does the following:
#   - Syntax check on the playbook
#   - Run the playbook
assert_playbook_runs

# An assertion that re-runs the playbook checking for no changes
assert_playbook_idempotent

# This is where you would add more assert statements for a "real" role
# Check https://github.com/nickjj/rolespec/README.rst#the-test-api for details
#
# You are also not limited to the test API, you can write any scripts you want
